language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.0.0
  - 1.5.0
  - 1.10.0
  - 1.15.0
  - 1.20.0
  - 1.25.0

matrix:
  include:
    - os: osx
    - os: windows

notifications:
  email:
    on_success: never
